<footer class="footer" class="wrapper">
    &copy; {{ moment(Date.now()).year() }} <a href="https://www.mipengine.org">mipengine</a> - <a href="https://github.com/mipengine"><i class="fa-github fa"></i></a>
</footer>

<!--[if lte IE 9]>
    <div class="update-ie">
        <p>您当前的浏览器版本过低，建议您升级浏览器版本，或者安装 <a href="https://www.baidu.com/s?wd=%E8%B0%B7%E6%AD%8C%E6%B5%8F%E8%A7%88%E5%99%A8%E4%B8%8B%E8%BD%BD">谷歌浏览器</a> 。</p>
    </div>
<![endif]-->

<mip-fixed type="gototop">
    <mip-gototop></mip-gototop>
</mip-fixed>

<mip-stats-baidu token="4e397f684261b9e4ff9d8ad4714f5b2b"></mip-stats-baidu>
<script src="https://c.mipcdn.com/static/v2/mip.js"></script>
<script src="https://c.mipcdn.com/static/v1/mip-sidebar/mip-sidebar.js"></script>
<script src="https://c.mipcdn.com/static/v1/mip-stats-baidu/mip-stats-baidu.js"></script>
<script src="https://c.mipcdn.com/static/v1/mip-gototop/mip-gototop.js"></script>
